# generated by export-spec-dsl
# 2026/4/14 17:25:44

class TypeScriptAstParser
  implements IAstParser
  - logger: Logger
  - extensionUri: vscode.Uri
  - parser: any
  - tsLanguage: any
  - jsLanguage: any
  - isInitialized: any
  + constructor(logger: Logger, extensionUri: vscode.Uri): any
    Scenario: 振る舞い
      かつ this.logger = logger;
      かつ this.extensionUri = extensionUri;
  - initParser(languageId: string): Promise<boolean>
    Scenario: 振る舞い
      もし (this.isInitialized && this.parser)
  - updateLanguage(languageId: string): void
    Scenario: 振る舞い
      もし (!this.parser)
      かつ const isJs = languageId === 'javascript' || languageId === 'javascriptreact';
      かつ this.parser.setLanguage(isJs ? this.jsLanguage : this.tsLanguage);
  + supports(languageId: string): boolean
    Scenario: 振る舞い
      ならば (戻す) return languageId === 'typescript' || languageId === 'javascript' ||
  + parse(uri: vscode.Uri, content: string): Promise<ClassInfo[]>
    Scenario: 振る舞い
      かつ const languageId = await this.detectLanguageId(uri);
      もし (!(await this.initParser(languageId)) || !this.parser)
  - detectLanguageId(uri: vscode.Uri): Promise<string>
    Scenario: 振る舞い
  - visitNode(node: Node, uri: vscode.Uri, classes: ClassInfo[]): void
    Scenario: 振る舞い
      もし (!node)
      もし (node.type === 'class_declaration' || node.type === 'class_expression' || node.type === 'enum_declaration')
      かつ ループ
  - extractClassInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: 振る舞い
      かつ const nameNode = node.childForFieldName('name');
      かつ const isAbstract = node.children.some(c => c.text === 'abstract');
      かつ const classInfo: ClassInfo = {
      かつ const heritage = node.children.find(c => c.type === 'class_heritage');
      もし (heritage)
      かつ const body = node.childForFieldName('body');
      もし (body)
      ならば (戻す) return classInfo;
  - extractInterfaceInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: 振る舞い
      かつ const nameNode = node.childForFieldName('name');
      かつ const classInfo: ClassInfo = {
      かつ const body = node.childForFieldName('body');
      もし (body)
      ならば (戻す) return classInfo;
  - extractMemberInfo(node: Node, classInfo: ClassInfo): void
    Scenario: 振る舞い
      もし (node.type === 'method_definition')
  - extractOperationInfo(node: Node): OperationInfo
    Scenario: 振る舞い
      かつ const nameNode = node.childForFieldName('name');
      かつ const accessibility = node.children.find(c => c.type === 'accessibility_modifier');
      かつ const bodyNode = node.childForFieldName('body');
      かつ this.logger.debug(`Extracting operation: ${nameNode ? nameNode.text : 'anonymous'} with accessibility: ${accessibility ? accessibility.text : 'public'}`);
      かつ this.logger.debug(`Operation body: ${bodyNode ? bodyNode.text : 'No body'}`);
      ならば (戻す) return {
  - extractWorkflow(bodyNode: Node): { nodes: any[], edges: any[] } | undefined
    Scenario: 振る舞い
      もし (!bodyNode || bodyNode.childCount === 0)
      かつ const nodes: any[] = [];
      かつ const edges: any[] = [];
      かつ const startId = cdt.createId();
      かつ nodes.push({ id: startId, type: 'start', label: 'Start', x: 200, y: 50 });
      かつ let currentY = 150;
      かつ let lastNodeId = startId;
      かつ ループ
      かつ const endId = cdt.createId();
      かつ nodes.push({ id: endId, type: 'end', label: 'End', x: 200, y: currentY });
      かつ edges.push({ from: lastNodeId, to: endId });
      ならば (戻す) return { nodes, edges };
  - mapStatementToWorkflowNode(node: Node): { type: string, label: string } | null
    Scenario: 振る舞い
  - extractAttributeInfo(node: Node): AttributeInfo
    Scenario: 振る舞い
      かつ const nameNode = node.childForFieldName('name');
      かつ const accessibility = node.children.find(c => c.type === 'accessibility_modifier');
      ならば (戻す) return {
  - extractParameters(node: Node | null): ParameterInfo[]
    Scenario: 振る舞い
      もし (!node)
      かつ const params: ParameterInfo[] = [];
      かつ ループ
      ならば (戻す) return params;
  - extractTypeName(node: Node | null): string
    Scenario: 振る舞い
      もし (!node)
      ならば (戻す) return node.text.replace(/^:/, '').trim();
  - extractModifiers(node: Node): string[]
    Scenario: 振る舞い
      かつ const mods: string[] = [];
      もし (node.children.some(c => c.text === 'static'))
      もし (node.children.some(c => c.text === 'readonly'))
      もし (node.children.some(c => c.text === 'abstract'))
      ならば (戻す) return mods;
  - convertRange(node: Node): vscode.Range
    Scenario: 振る舞い
      ならば (戻す) return new vscode.Range(
