# generated by export-spec-dsl
# 2026/4/15 0:53:03

// ドメインクラス
class TypeScriptAstParser
  implements IAstParser
  - logger: Logger
  - extensionUri: vscode.Uri
  - parser: any
  - tsLanguage: any
  - jsLanguage: any
  - isInitialized: any
  + constructor(logger: Logger, extensionUri: vscode.Uri): any
    Scenario: 振る舞い
      And this.logger = logger;
      And this.extensionUri = extensionUri;
  - initParser(languageId: string): Promise<boolean>
    Scenario: web-tree-sitterおよび言語モジュールを初期化する
      Given web-tree-sitterおよび言語モジュールが初期化されていないこと
      When initParser()を呼び出す
      How
        "web-tree-sitterおよび言語モジュールを初期化すること"
      Then web-tree-sitterおよび言語モジュールが初期化されること
      Why web-tree-sitterおよび言語モジュールが初期化されていないとASTを構築できないため
  - updateLanguage(languageId: string): void
    Scenario: 振る舞い
      When (!this.parser)
      And const isJs = languageId === 'javascript' || languageId === 'javascriptreact';
      And this.parser.setLanguage(isJs ? this.jsLanguage : this.tsLanguage);
  + supports(languageId: string): boolean
    Scenario: 振る舞い
      Then return languageId === 'typescript' || languageId === 'javascript' ||
  + parse(uri: vscode.Uri, content: string): Promise<ClassInfo[]>
    Scenario: ASTをパースしてクラス情報を抽出する
      Given コードの文字列とURIが与えられていること
      When tree-sitterでパースを実行する
      How
        ""指定された言語でWASMをロードしツリーを生成する""
        ""visitNodeを用いてASTを再帰的に走査し、クラスやメソッドを抽出する""
      Then ClassInfo配列が生成されること
      Why "クラス図として可視化するための基礎データ構造を作るため"
  - detectLanguageId(uri: vscode.Uri): Promise<string>
    Scenario: 振る舞い
  - visitNode(node: Node, uri: vscode.Uri, classes: ClassInfo[]): void
    Scenario: 振る舞い
      When (!node)
      When (node.type === 'class_declaration' || node.type === 'class_expression' || node.type === 'enum_declaration')
      And ループ
  - extractClassInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: クラス宣言を抽出する（通常）
      Given class_declaration ノードが渡されたこと
      When extractClassInfo() を呼び出す
      Then nameと attributes をもつ ClassInfo が返ること
      Why 通常クラスの構造をグラフィカルに表現するため
    Scenario: 抽象クラスを抽出する
      Given abstract 修飾子を持つノードが渡されたこと
      When extractClassInfo() を呼び出す
      Then kind が "abstract" に設定されること
    Scenario: 継承とインターフェースのマッピング
      Given extends や implements を持つノードであること
      When extractClassInfo() を呼び出す
      How
        ""class_heritage を解析して baseClass と interfaces を特定する""
      Then ClassInfo 内の依存関係が正しく設定されること
  - extractPrecedingComments(node: Node): string
    Scenario: 振る舞い
      And let text = '';
      And let prev = node.previousSibling;
      And ループ
      Then return text;
  - extractInterfaceInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: 振る舞い
      And const nameNode = node.childForFieldName('name');
      And const classInfo: ClassInfo = {
      And const body = node.childForFieldName('body');
      When (body)
      Then return classInfo;
  - extractMemberInfo(node: Node, classInfo: ClassInfo): void
    Scenario: 振る舞い
      When (node.type === 'method_definition')
  - extractOperationInfo(node: Node): OperationInfo
    Scenario: 振る舞い
      And const nameNode = node.childForFieldName('name');
      And const accessibility = node.children.find(c => c.type === 'accessibility_modifier');
      And const bodyNode = node.childForFieldName('body');
      And this.logger.debug(`Extracting operation: ${nameNode ? nameNode.text : 'anonymous'} with accessibility: ${accessibility ? accessibility.text : 'public'}`);
      And this.logger.debug(`Operation body: ${bodyNode ? bodyNode.text : 'No body'}`);
      And let workflowAst = bodyNode ? this.extractWorkflow(bodyNode) : undefined;
      And const commentText = this.extractPrecedingComments(node);
      And const commentWorkflow = CommentParser.parseOperationComments(commentText);
      Then return {
  - extractWorkflow(bodyNode: Node): { nodes: any[], edges: any[] } | undefined
    Scenario: 振る舞い
      When (!bodyNode || bodyNode.childCount === 0)
      And const nodes: any[] = [];
      And const edges: any[] = [];
      And const startId = cdt.createId();
      And nodes.push({ id: startId, type: 'start', label: 'Start', x: 200, y: 50 });
      And let currentY = 150;
      And let lastNodeId = startId;
      And ループ
      And const endId = cdt.createId();
      And nodes.push({ id: endId, type: 'end', label: 'End', x: 200, y: currentY });
      And edges.push({ from: lastNodeId, to: endId });
      Then return { nodes, edges };
  - mapStatementToWorkflowNode(node: Node): { type: string, label: string } | null
    Scenario: 振る舞い
  - extractAttributeInfo(node: Node): AttributeInfo
    Scenario: 振る舞い
      And const nameNode = node.childForFieldName('name');
      And const accessibility = node.children.find(c => c.type === 'accessibility_modifier');
      And const attributeInfo: AttributeInfo = {
      And const commentText = this.extractPrecedingComments(node);
      And const needs = CommentParser.parseMemberComments(commentText);
      When (needs)
      Then return attributeInfo;
  - extractParameters(node: Node | null): ParameterInfo[]
    Scenario: 振る舞い
      When (!node)
      And const params: ParameterInfo[] = [];
      And ループ
      Then return params;
  - extractTypeName(node: Node | null): string
    Scenario: 振る舞い
      When (!node)
      Then return node.text.replace(/^:/, '').trim();
  - extractModifiers(node: Node): string[]
    Scenario: 振る舞い
      And const mods: string[] = [];
      When (node.children.some(c => c.text === 'static'))
      When (node.children.some(c => c.text === 'readonly'))
      When (node.children.some(c => c.text === 'abstract'))
      Then return mods;
  - convertRange(node: Node): vscode.Range
    Scenario: 振る舞い
      Then return new vscode.Range(
