# generated by export-spec-dsl
# 2026/4/24 19:02:54

// ドメインクラス
class TypeScriptAstParser
  implements IAstParser
  - logger: Logger
  - extensionUri: vscode.Uri
  - parser: any
  - tsLanguage: any
  - jsLanguage: any
  - isInitialized: any
  + constructor(logger: Logger, extensionUri: vscode.Uri): any
    Scenario: 振る舞い
      And loggerにloggerを設定する
      And extensionUriにextensionUriを設定する
  - initParser(languageId: string): Promise<boolean>
    Scenario: web-tree-sitterおよび言語モジュールを初期化する
      Given web-tree-sitterおよび言語モジュールが初期化されていないこと
      When initParser()を呼び出す
      How
        "web-tree-sitterおよび言語モジュールを初期化すること"
      Then web-tree-sitterおよび言語モジュールが初期化されること
      Why web-tree-sitterおよび言語モジュールが初期化されていないとASTを構築できないため
    Flow:
      var normalized:boolean = amount > 0
      if normalized
        do this.markCompleted()
        for item in this.items
          do item.process()
          if item.invalid
            break
          end
        end
        return true
      else
        do this.markRejected()
        return false
      end
      switch this.status
        case "pending":
          do this.initialize()
        case "active":
          do this.execute()
          return true
        default:
          return false
      end
  - updateLanguage(languageId: string): void
    Scenario: 振る舞い
      When (!this.parser)
      And parser の setLanguage を呼び出す
  + supports(languageId: string): boolean
    Scenario: 振る舞い
      Then languageId === 'typescript' ||…を返す
  + parse(uri: vscode.Uri, content: string): Promise<ClassInfo[]>
    Scenario: ASTをパースしてクラス情報を抽出する
      Given コードの文字列とURIが与えられていること
      When tree-sitterでパースを実行する
      How
        ""指定された言語でWASMをロードしツリーを生成する""
        ""visitNodeを用いてASTを再帰的に走査し、クラスやメソッドを抽出する""
      Then ClassInfo配列が生成されること
      Why "クラス図として可視化するための基礎データ構造を作るため"
  - detectLanguageId(uri: vscode.Uri): Promise<string>
  - visitNode(node: Node, uri: vscode.Uri, classes: ClassInfo[]): void
    Scenario: 振る舞い
      When (!node)
      When (node.type === 'class_declaration' || no…
      And iをカウントアップしながら繰り返す
  - extractClassInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: クラス宣言を抽出する（通常）
      Given class_declaration ノードが渡されたこと
      When extractClassInfo() を呼び出す
      Then nameと attributes をもつ ClassInfo が返ること
      Why 通常クラスの構造をグラフィカルに表現するため
    Scenario: 抽象クラスを抽出する
      Given abstract 修飾子を持つノードが渡されたこと
      When extractClassInfo() を呼び出す
      Then kind が "abstract" に設定されること
    Scenario: 継承とインターフェースのマッピング
      Given extends や implements を持つノードであること
      When extractClassInfo() を呼び出す
      How
        ""class_heritage を解析して baseClass と interfaces を特定する""
      Then ClassInfo 内の依存関係が正しく設定されること
  - extractPrecedingComments(node: Node): string
    Scenario: 振る舞い
      Given text, prev を初期化する
      And (prev && prev.type === 'comment')の間、繰り返す
      Then textを返す
  - extractInterfaceInfo(node: Node, uri: vscode.Uri): ClassInfo
    Scenario: 振る舞い
      Given nameNode, classInfo, body を初期化する
      When (body)
      Then classInfoを返す
  - extractMemberInfo(node: Node, classInfo: ClassInfo): void
    Scenario: 振る舞い
      When (node.type === 'method_definition')
  - extractOperationInfo(node: Node): OperationInfo
    Scenario: 振る舞い
      Given nameNode, accessibility, bodyNode を初期化する
      And logger の debug を呼び出す
      And logger の debug を呼び出す
      Then extractModifiers(node),
      …を返す
  - extractWorkflow(bodyNode: Node): { nodes: any[], edges: any[] } | undefined
    Scenario: 振る舞い
      When (!bodyNode || bodyNode.childCount === 0)
      And iをカウントアップしながら繰り返す
      When stmtsが空
      And (
            givenEnd < stmts.length &&…の間、繰り返す
      When middleNodesが空
      And nodes の push を呼び出す
      When (hasGiven)
      And middleNodesの各mappedを処理する
      When (hasReturn)
      And nodes の push を呼び出す
      And edges の push を呼び出す
      Then nodes, edgesを返す
  - mapStatementToWorkflowNode(node: Node): { type: string, label: string } | null
  - isGuardBody(node: Node): boolean
    Scenario: 振る舞い
      Given stmts を初期化する
      When stmtsが空
      Then stmts.everyを返す
  - summarizeCondition(raw: string): string
    Scenario: 振る舞い
      Given t を初期化する
      And (notMatch)の場合は早期終了
      And (emptyMatch)の場合は早期終了
      And (nullMatch)の場合は早期終了
      And (matchExpr)の場合は早期終了
      And (identOnly)の場合は早期終了
      And (lhsMatch)の場合は早期終了
      Then length > 40 ? t.sliceを返す
  - extractLoopTarget(init: string): string
    Scenario: 振る舞い
      Given m を初期化する
      Then m ? m : 'インデックス'を返す
  - summarizeIdentifier(raw: string): string
    Scenario: 振る舞い
      When (!raw)
      And tにt.replaceを設定する
      And tにt.replaceを設定する
      And tにt.replaceを設定する
      And tにparts.sliceを設定する
      When (t.length > 30)
      Then tを返す
  - summarizeReturnExpr(node: Node): string
    Scenario: 振る舞い
      Given raw を初期化する
      And (objMatch)の場合は早期終了
      And (newMatch)の場合は早期終了
      And (raw.startsWith('['))の場合は早期終了
      And (raw === 'null' || raw === 'undefined')の場合は早期終了
      Then summarizeIdentifierを返す
  - summarizeCallExpression(funcName: string): string
    Scenario: 振る舞い
      Given cleaned, parts, method を初期化する
      And (receiver)の場合は早期終了
      Then `${method} を呼び出す`を返す
  - extractAttributeInfo(node: Node): AttributeInfo
    Scenario: 振る舞い
      Given nameNode, accessibility, attributeInfo を初期化する
      When (needs)
      Then attributeInfoを返す
  - extractParameters(node: Node | null): ParameterInfo[]
    Scenario: 振る舞い
      When (!node)
      And iをカウントアップしながら繰り返す
      Then paramsを返す
  - extractTypeName(node: Node | null): string
    Scenario: 振る舞い
      When (!node)
      Then text.replaceを返す
  - extractModifiers(node: Node): string[]
    Scenario: 振る舞い
      Given mods を初期化する
      When (node.children.some(c => c.text === 'sta…
      When (node.children.some(c => c.text === 'rea…
      When (node.children.some(c => c.text === 'abs…
      Then modsを返す
  - convertRange(node: Node): vscode.Range
    Scenario: 振る舞い
      Then vscodeを返す
