import { Command } from "./Command";
import { HandlerResult } from "../handler-registry";
import { DomainModel } from "../DomainModel";
import { DesignGraphAggregate } from "../DesignGraphModel";
import { CliCommandType } from "../CliParser";
import { ClassDiagramService } from "../application/ClassDiagramService";
import {
    ClassInfo,
    ClassMember,
    ClassOperation,
    Relationship,
    visibilitySymbol,
} from "../class-diagram-types";
import { postMessage } from "../../../frontend/src/bridge/vscode-bridge";

/**
 * ExportSpecDslCommand
 *
 * 現在のクラス図モデルを import-spec-dsl で読み戻せるDSL形式で出力する。
 * export-spec（仕様書Markdown）とは異なり、ラウンドトリップを目的とした
 * 機械可読フォーマット。
 *
 * Usage:
 *   export-spec-dsl [<outputPath>]
 *
 * Examples:
 *   export-spec-dsl                  → stdout に出力
 *   export-spec-dsl ./diagram.md     → ファイルに保存
 *
 * 出力フォーマット:
 *   # generated by export-spec-dsl
 *
 *   abstract class ClassName
 *     - fieldName: Type
 *     + methodName(param: Type): ReturnType
 *     extends BaseClass
 *     implements InterfaceA, InterfaceB
 *
 *   # Relations
 *   SourceClass -> TargetClass
 *   SourceClass +> TargetClass :label 1 *
 */
export class ExportSpecDslCommand extends Command {
    readonly type: CliCommandType = "EXPORT_SPEC_DSL";

    readonly outputPath: string | undefined;

    constructor(raw: string, outputPath?: string) {
        super(raw);
        this.outputPath = outputPath;
    }

    execute(model: DomainModel, graph?: DesignGraphAggregate): HandlerResult {
        const service = new ClassDiagramService(model);
        const currentModel = service.getModel();

        const dsl = generateDsl(currentModel);

        if (this.outputPath) {
            postMessage({
                command: 'exportSpecDsl',
                payload: {
                    dsl,
                    fileName: this.outputPath
                }
            });
        } else {
            postMessage({ command: 'log', level: 'info', text: dsl });
        }


        const ev = { type: "EXPORT_SPEC_DSL" };
        return { model: currentModel, events: [ev] } as any;
    }
}

// ============================================================
// DSL Generator
// ============================================================

function generateDsl(model: DomainModel): string {
    const classes = model.getClasses();
    // generalization / realization は extends / implements として
    // クラスブロック内に出力するため、明示リレーションからは除外する
    const explicitRelTypes = new Set(["association", "aggregation", "composition", "dependency"]);
    const relationships = model
        .detectRelationships()
        .filter((r) => explicitRelTypes.has(r.type));

    const lines: string[] = [];

    lines.push("# generated by export-spec-dsl");
    lines.push(`# ${new Date().toLocaleString("ja-JP")}`);
    lines.push("");

    // ---- クラスブロック ----
    for (const cls of classes) {
        lines.push(...renderClassDsl(cls, model));
    }

    // ---- 明示リレーション ----
    if (relationships.length > 0) {
        lines.push("# Relations");
        lines.push("");
        for (const rel of relationships) {
            lines.push(renderRelationDsl(rel, model));
        }
        lines.push("");
    }

    return lines.join("\n");
}

// ============================================================
// Class Block Renderer
// ============================================================

function renderClassDsl(cls: ClassInfo, model: DomainModel): string[] {
    const lines: string[] = [];

    // クラス宣言行
    const abstractPrefix = cls.isAbstract ? "abstract " : "";
    lines.push(`${abstractPrefix}${cls.kind} ${cls.name}`);

    // メンバ（属性）
    for (const m of cls.members) {
        lines.push(`  ${renderMemberDsl(m)}`);
    }

    // 操作（メソッド）
    for (const op of cls.operations) {
        lines.push(`  ${renderOperationDsl(op)}`);
    }

    // 継承
    if (cls.baseClassId) {
        const base = model.findClassById(cls.baseClassId);
        if (base) {
            lines.push(`  extends ${base.name}`);
        }
    }

    // インターフェース実装
    if (cls.interfaces.length > 0) {
        const names = cls.interfaces
            .map((id) => model.findClassById(id)?.name ?? id)
            .join(", ");
        lines.push(`  implements ${names}`);
    }

    lines.push("");
    return lines;
}

// ============================================================
// Member / Operation DSL Renderers
// ============================================================

function renderMemberDsl(m: ClassMember): string {
    const vis = visibilitySymbol(m.visibility);
    const modifier = m.isStatic ? "s " : m.isAbstract ? "a " : "";
    return `${vis} ${modifier}${m.name}: ${m.type}`;
}

function renderOperationDsl(op: ClassOperation): string {
    const vis = visibilitySymbol(op.visibility);
    const modifier = op.isStatic ? "s " : op.isAbstract ? "a " : "";
    const params = op.parameters
        .map((p) => `${p.name}: ${p.type}`)
        .join(", ");
    return `${vis} ${modifier}${op.name}(${params}): ${op.returnType}`;
}

// ============================================================
// Relation DSL Renderer
// ============================================================

function renderRelationDsl(rel: Relationship, model: DomainModel): string {
    const src = model.findClassById(rel.sourceId)?.name ?? rel.sourceId;
    const tgt = model.findClassById(rel.targetId)?.name ?? rel.targetId;

    const symbolMap: Record<string, string> = {
        association: "->",
        aggregation: "+>",
        composition: "*>",
        dependency: "-/>",
    };
    const symbol = symbolMap[rel.type] ?? "->";

    // ラベル・多重度があれば付加
    const label = rel.label ? ` :${rel.label}` : "";
    const multiplicity =
        rel.sourceMultiplicity || rel.targetMultiplicity
            ? ` ${rel.sourceMultiplicity ?? "1"} ${rel.targetMultiplicity ?? "1"}`
            : "";

    return `${src} ${symbol} ${tgt}${label}${multiplicity}`;
}