import { Command } from "./Command";
import { HandlerResult } from "../handler-registry";
import { DomainModel } from "../DomainModel";
import { CliCommandType } from "../CliParser";
import { ClassDiagramService } from "../application/ClassDiagramService";
import {
    ClassInfo,
    ClassMember,
    ClassOperation,
    Relationship,
    visibilitySymbol,
} from "../class-diagram-types";
import { postMessage } from "../../../frontend/src/bridge/vscode-bridge";

/**
 * ExportSpecDslCommand
 *
 * 現在のクラス図モデルを import-spec-dsl で読み戻せるDSL形式で出力する。
 * export-spec（仕様書Markdown）とは異なり、ラウンドトリップを目的とした
 * 機械可読フォーマット。
 *
 * Usage:
 *   export-spec-dsl [<outputPath>]
 *
 * Examples:
 *   export-spec-dsl                  → stdout に出力
 *   export-spec-dsl ./diagram.md     → ファイルに保存
 *
 * 出力フォーマット:
 *   # generated by export-spec-dsl
 *
 *   abstract class ClassName
 *     - fieldName: Type
 *     + methodName(param: Type): ReturnType
 *     extends BaseClass
 *     implements InterfaceA, InterfaceB
 *
 *   # Relations
 *   SourceClass -> TargetClass
 *   SourceClass +> TargetClass :label 1 *
 */
export class ExportSpecDslCommand extends Command {
    readonly type: CliCommandType = "EXPORT_SPEC_DSL";

    readonly outputPath: string | undefined;

    constructor(raw: string, outputPath?: string) {
        super(raw);
        this.outputPath = outputPath;
    }

    execute(model: DomainModel): HandlerResult {
        const service = new ClassDiagramService(model);
        const currentModel = service.getModel();

        const dsl = currentModel.toDSL();

        if (this.outputPath) {
            postMessage({
                command: 'exportSpecDsl',
                payload: {
                    dsl,
                    fileName: this.outputPath
                }
            });
        } else {
            postMessage({ command: 'log', level: 'info', text: dsl });
        }


        const ev = { type: "EXPORT_SPEC_DSL" };
        return { success: true, model: currentModel, events: [] };
    }
}